### ISSUE TITLE
Cannot find module './settings'

### ISSUE THREAD

**Issue by chaitanya642000** [agenda/agenda-rest#122]
client@0.1.0 start C:\Users\hp\Desktop\SocialNetwork\client
> react-scripts start

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './settings'
Require stack:
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\@nodelib\fs.walk\out\index.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\fast-glob\out\readers\stream.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\fast-glob\out\providers\async.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\fast-glob\out\index.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\globby\index.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\react-dev-utils\globby.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\react-scripts\scripts\start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\hp\Desktop\SocialNetwork\client\node_modules\@nodelib\fs.walk\out\index.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\@nodelib\\fs.walk\\out\\index.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\fast-glob\\out\\readers\\stream.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\fast-glob\\out\\providers\\async.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\fast-glob\\out\\index.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\globby\\index.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\react-dev-utils\\globby.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\react-scripts\\scripts\\utils\\verifyTypeScriptSetup.js',
    'C:\\Users\\hp\\Desktop\\SocialNetwork\\client\\node_modules\\react-scripts\\scripts\\start.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!

C:\Users\hp\Desktop\SocialNetwork>npm start --prefix client

> client@0.1.0 start C:\Users\hp\Desktop\SocialNetwork\client
> react-scripts start

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './settings'
Require stack:
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\@nodelib\fs.walk\out\index.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\fast-glob\out\readers\stream.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\fast-glob\out\providers\async.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\fast-glob\out\index.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\globby\index.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\react-dev-utils\globby.js
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js        
- C:\Users\hp\Desktop\SocialNetwork\client\node_modules\react-scripts\scripts\start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)

node version:v14.15.3
npm version:6.14.9

**Comment by simllll** [comment]
This repository has been archived. agenda-rest is now part of the Agenda monorepo.

**New location:** https://github.com/agenda/agenda/tree/main/packages/agenda-rest

Please open any new issues or PRs in the main Agenda repository: https://github.com/agenda/agenda/issues
