### ISSUE TITLE
Cannot find module '../settings'

### ISSUE THREAD

**Issue by campbellrw** [agenda/agenda-rest#15]
Following instructions in README, did this:

> npm install -g agenda-rest
> agenda-rest --dbhost my.ip.here --dbname agenda

and get the following:

module.js:538
    throw err;
    ^

Error: Cannot find module '../settings'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/agenda-rest/dist/index.js:1:1547)
    at o (/usr/lib/node_modules/agenda-rest/dist/index.js:1:422)
    at Object.<anonymous> (/usr/lib/node_modules/agenda-rest/dist/index.js:1:4530)
    at o (/usr/lib/node_modules/agenda-rest/dist/index.js:1:422)
    at Object.defineProperty.value (/usr/lib/node_modules/agenda-rest/dist/index.js:1:843)
    at /usr/lib/node_modules/agenda-rest/dist/index.js:1:852

Am I missing something that's not included in the 'npm install' ?

OS: Ubuntu 16.04 LTS
Node: 8.9.3
NPM: 5.8.0

**Comment by 2bigO** [comment]
Thanks for reporting @campbellrw.
@farhoud could you take a look?

**Comment by OmgImAlexis** [comment]
You never added the file to npm.

https://github.com/agenda/agenda-rest/blob/master/package.json#L19

**Comment by 2bigO** [comment]
Great observation @OmgImAlexis! I don't have access to my PC for the next few days. Could you please add this and publish a new version?

**Comment by 2bigO** [comment]
@campbellrw this should be fixed in `v0.7.4` which you can get with `npm update agenda-rest`, appreciate if you could confirm. Please feel free to reopen if the issue persisted.
