### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by joehuangcoding** [agenda/agenda-rest#53]
When I do npm run start, I am getting this error. Any ideas? 

/***************************************************************************************************/
async * [Symbol.asyncIterator]() {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.pythonic (C:\Users\joe.h\Desktop\agenda_rest\agenda-rest\dist\index.js:564:18)

/***************************************************************************************************/

**Comment by joehuangcoding** [comment]
You need node 10.

**Comment by joehuangcoding** [comment]
You need node 10.
